### ISSUE TITLE
Demo app not running: possibly npm package issues

### ISSUE THREAD

**Issue by netsrotr** [syncfusion/angular2-seeds#40]
If I follow the instructions e.g. at [https://help.syncfusion.com/angular/gantt/getting-started](https://help.syncfusion.com/angular/gantt/getting-started), that starts with a git-clone of angular2-seeds, the resulting app loads forever. No demo content displayed.
I think, some of the npm package(s) version are wrong, or whatever. Can you please have a look? 

I just thought before I start with our own angular 5 project to include the gantt control I will have a "test-bed" to play with the options.

**Comment by AbinayaSubbiah** [comment]
Hi @netsrotr 

We sorry for the inconvenience caused.

The getting started for the [Gantt](https://help.syncfusion.com/angular/gantt/getting-started) is not updated, since it may cause issue. We will check and update our getting started ASAP. For your convenience we prepared seed application with Gantt component. Please refer below link for the sample.

[seed-application](http://www.syncfusion.com/downloads/support/directtrac/general/ze/angular2-seeds-300141425.zip)

You can refer general getting started with below link.

https://help.syncfusion.com/angular/gettingstarted/getting-started-webpack

Also refer below link for Syncfusion Angular components demos.

http://ng2jq.syncfusion.com/

Please let us know if you need further assist on this.
